export function renderMetricsDashboard(): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>System Metrics · SSO Provider</title>
  <style>
    :root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#172033;background:#f4f7fb;--blue:#2563eb;--navy:#172033;--muted:#667085;--line:#dce3ee;--green:#18794e;--red:#b42318;--amber:#9a6700}*{box-sizing:border-box}body{margin:0;background:#f4f7fb}.topbar{background:#fff;border-bottom:1px solid var(--line)}.shell{width:min(1180px,calc(100% - 36px));margin:auto}.topbar .shell{height:72px;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:12px}.mark{width:42px;height:42px;display:grid;place-items:center;border-radius:12px;background:var(--blue);color:#fff;font-weight:800}.brand strong,.brand span{display:block}.brand span{font-size:12px;color:var(--muted)}a{color:var(--blue);font-weight:700;text-decoration:none}main{padding:30px 0 50px}.heading{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.eyebrow{margin:0 0 6px;color:var(--blue);font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}h1,h2,p{margin-top:0}h1{margin-bottom:5px}.muted{color:var(--muted)}.status{display:flex;align-items:center;gap:7px;font-size:13px}.dot{width:9px;height:9px;border-radius:50%;background:var(--green)}.dot.bad{background:var(--red)}.grid{display:grid;gap:16px}.metrics{grid-template-columns:repeat(4,minmax(0,1fr))}.card{padding:21px;background:#fff;border:1px solid var(--line);border-radius:14px;box-shadow:0 4px 18px rgba(23,32,51,.05)}.label{color:var(--muted);font-size:12px;font-weight:750;letter-spacing:.07em;text-transform:uppercase}.value{margin:7px 0 2px;font-size:30px;font-weight:800}.detail{font-size:12px;color:var(--muted)}.wide{margin-top:16px;grid-template-columns:1.5fr 1fr}.card-header{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.card-header h2{margin:0;font-size:18px}.chart{width:100%;height:220px;border-radius:8px;background:linear-gradient(#f8fafc,#fff)}table{width:100%;border-collapse:collapse}th,td{padding:12px 10px;border-bottom:1px solid var(--line);text-align:left}th{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.07em}.badge{display:inline-block;padding:4px 9px;border-radius:999px;font-size:12px;font-weight:750;background:#e7f7ef;color:var(--green)}.badge.bad{background:#feeceb;color:var(--red)}.error{display:none;margin-bottom:16px;padding:12px 15px;border-radius:9px;background:#feeceb;color:var(--red)}.footer{margin-top:16px;font-size:12px;color:var(--muted)}@media(max-width:850px){.metrics,.wide{grid-template-columns:1fr 1fr}}@media(max-width:560px){.metrics,.wide{grid-template-columns:1fr}.heading{display:block}.status{margin-top:12px}.topbar .shell{height:auto;padding:14px 0}}
  </style>
</head>
<body>
  <header class="topbar"><div class="shell"><div class="brand"><div class="mark">SSO</div><div><strong>System Metrics</strong><span>Auth Provider observability</span></div></div><a href="/">Back to SSO Portal</a></div></header>
  <main class="shell"><div class="heading"><div><p class="eyebrow">Live operations</p><h1>System health at a glance</h1><p class="muted">HTTP measurements use a rolling one-minute window. Queue values come directly from RabbitMQ.</p></div><div class="status"><span class="dot" id="live-dot"></span><span id="updated">Connecting…</span></div></div><div class="error" id="error">Metrics are temporarily unavailable. Retrying automatically.</div>
    <div class="grid metrics"><section class="card"><div class="label">Request rate</div><div class="value"><span id="rate">—</span></div><div class="detail">requests in the last minute</div></section><section class="card"><div class="label">Average latency</div><div class="value"><span id="latency">—</span> <small>ms</small></div><div class="detail">P95: <span id="p95">—</span> ms</div></section><section class="card"><div class="label">HTTP errors</div><div class="value"><span id="errors">—</span></div><div class="detail"><span id="error-rate">—</span>% of recent requests</div></section><section class="card"><div class="label">Total queue depth</div><div class="value"><span id="queue-total">—</span></div><div class="detail" id="worker-state">Checking worker</div></section></div>
    <div class="grid wide"><section class="card"><div class="card-header"><h2>Latency trend</h2><span class="detail">Average · last 30 samples</span></div><canvas class="chart" id="chart"></canvas></section><section class="card"><div class="card-header"><h2>RabbitMQ queues</h2><span class="badge" id="broker-badge">Available</span></div><table><thead><tr><th>Queue</th><th>Ready messages</th></tr></thead><tbody><tr><td>Main events</td><td id="main-depth">—</td></tr><tr><td>Scheduled retries</td><td id="retry-depth">—</td></tr><tr><td>Dead letters</td><td id="dlq-depth">—</td></tr><tr><td>Main consumers</td><td id="consumers">—</td></tr></tbody></table></section></div><div class="footer">Process uptime: <span id="uptime">—</span> · Total measured requests: <span id="total-requests">—</span> · Prometheus endpoint: <a href="/metrics/prometheus">/metrics/prometheus</a></div>
  </main>
  <script>
const history=[];const byId=id=>document.getElementById(id);const value=(input,fallback='—')=>input===null||input===undefined?fallback:String(input);const duration=seconds=>{const hours=Math.floor(seconds/3600);const minutes=Math.floor(seconds%3600/60);return hours+'h '+minutes+'m'};
function drawChart(){const canvas=byId('chart');const ratio=window.devicePixelRatio||1;const width=canvas.clientWidth;const height=canvas.clientHeight;canvas.width=width*ratio;canvas.height=height*ratio;const context=canvas.getContext('2d');context.scale(ratio,ratio);context.clearRect(0,0,width,height);context.strokeStyle='#dce3ee';context.lineWidth=1;for(let row=1;row<4;row++){const y=height*row/4;context.beginPath();context.moveTo(0,y);context.lineTo(width,y);context.stroke()}if(history.length<2)return;const maximum=Math.max(1,...history);context.strokeStyle='#2563eb';context.lineWidth=3;context.lineJoin='round';context.beginPath();history.forEach((item,index)=>{const x=index*width/(history.length-1);const y=height-12-(item/maximum)*(height-24);if(index===0)context.moveTo(x,y);else context.lineTo(x,y)});context.stroke()}
async function refresh(){try{const response=await fetch('/metrics/data',{cache:'no-store'});if(!response.ok)throw new Error('Metrics request failed');const data=await response.json();byId('error').style.display='none';byId('live-dot').classList.remove('bad');byId('updated').textContent='Updated '+new Date(data.generatedAt).toLocaleTimeString('en-GB');byId('rate').textContent=data.http.requestsLastMinute;byId('latency').textContent=data.http.averageLatencyMilliseconds;byId('p95').textContent=data.http.p95LatencyMilliseconds;byId('errors').textContent=data.http.errorsLastMinute;byId('error-rate').textContent=data.http.errorRatePercent;byId('total-requests').textContent=data.http.totalRequests;byId('uptime').textContent=duration(data.uptimeSeconds);const queues=data.queues;const depths=[queues.mainDepth,queues.retryDepth,queues.deadLetterDepth];byId('queue-total').textContent=queues.available?depths.reduce((sum,item)=>sum+(item||0),0):'—';byId('main-depth').textContent=value(queues.mainDepth);byId('retry-depth').textContent=value(queues.retryDepth);byId('dlq-depth').textContent=value(queues.deadLetterDepth);byId('consumers').textContent=value(queues.consumerCount);byId('worker-state').textContent=!queues.available?'Broker unavailable':queues.consumerCount>0?'Worker is consuming':'No active worker consumer';byId('broker-badge').textContent=queues.available?'Available':'Unavailable';byId('broker-badge').className='badge'+(queues.available?'':' bad');history.push(data.http.averageLatencyMilliseconds);if(history.length>30)history.shift();drawChart()}catch(error){byId('error').style.display='block';byId('live-dot').classList.add('bad');byId('updated').textContent='Waiting to reconnect'}}
refresh();setInterval(refresh,3000);window.addEventListener('resize',drawChart);
  </script>
</body>
</html>`;
}
