export function renderMfaSetup(input: {
  enabled: boolean;
  recoveryCodesRemaining: number;
  secret?: string;
  provisioningUri?: string;
}): string {
  const content = input.enabled
    ? `<div class="success"><strong>MFA is enabled</strong><span>Your account requires an authenticator code after every valid password.</span></div><p class="muted">Unused recovery codes: <strong>${input.recoveryCodesRemaining}</strong></p><a class="button secondary" href="/">Back to account</a>`
    : `<ol><li>Open your authenticator app and choose to add an account manually.</li><li>Enter the setup key below and select <strong>Time based</strong>.</li><li>Enter the current 6-digit code to finish setup.</li></ol><div class="secret"><span>Setup key</span><strong id="setup-key">${input.secret ?? ''}</strong><button type="button" id="copy">Copy</button></div><a class="app-link" href="${input.provisioningUri ?? '#'}">Open in authenticator app</a><form id="enroll-form"><label for="code">Verification code</label><input id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required placeholder="000000"><button class="button" id="submit" type="submit">Enable MFA</button><div class="error" id="error" role="alert"></div></form><section class="recovery hidden" id="recovery"><h2>Save your recovery codes</h2><p>Each code works once. Store them somewhere safe before leaving this page.</p><div class="codes" id="codes"></div><a class="button" href="/">I saved these codes</a></section>`;
  const script = input.enabled
    ? ''
    : `<script>
const form=document.getElementById('enroll-form');const submit=document.getElementById('submit');const errorBox=document.getElementById('error');document.getElementById('copy').addEventListener('click',()=>navigator.clipboard?.writeText(document.getElementById('setup-key').textContent.replaceAll(' ','')));form.addEventListener('submit',async event=>{event.preventDefault();submit.disabled=true;errorBox.textContent='';try{const response=await fetch('/auth/mfa/enroll',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:form.code.value})});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message||'The verification code could not be accepted.');form.classList.add('hidden');document.getElementById('recovery').classList.remove('hidden');document.getElementById('codes').innerHTML=body.recoveryCodes.map(code=>'<code>'+code+'</code>').join('')}catch(error){errorBox.textContent=error instanceof Error?error.message:'MFA setup failed.';submit.disabled=false}});
</script>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Set up MFA · SSO Portal</title><style>:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0;min-height:100vh;padding:35px 20px;background:radial-gradient(circle at top,#dbeafe 0,#f4f7fb 44%)}main{width:min(100%,620px);margin:auto;padding:32px;background:#fff;border:1px solid #dce3ee;border-radius:20px;box-shadow:0 24px 60px rgba(30,64,175,.12)}.eyebrow{margin:0 0 7px;color:#2563eb;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}h1{margin:0 0 10px}.muted,p,ol{color:#667085;line-height:1.6}ol{padding-left:22px}.secret{display:grid;grid-template-columns:1fr auto;gap:7px 12px;margin:22px 0;padding:16px;border-radius:12px;background:#eff6ff}.secret span{grid-column:1/-1;color:#667085;font-size:12px;font-weight:700;text-transform:uppercase}.secret strong{font:700 16px Consolas,monospace;letter-spacing:.1em;overflow-wrap:anywhere}.secret button{border:0;background:transparent;color:#2563eb;font-weight:750}.app-link{display:inline-block;margin-bottom:18px;color:#2563eb;font-weight:700}label{display:block;margin:16px 0 7px;font-weight:700}input{width:100%;padding:12px 14px;border:1px solid #cbd5e1;border-radius:10px;font:inherit}.button{display:inline-block;margin-top:18px;border:0;border-radius:10px;padding:12px 16px;background:#2563eb;color:#fff;font:inherit;font-weight:750;text-decoration:none;cursor:pointer}.button.secondary{background:#e8effd;color:#1e4db7}.error{min-height:20px;margin-top:12px;color:#b42318}.hidden{display:none}.recovery{margin-top:20px}.codes{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:16px;border-radius:12px;background:#f4f7fb}.codes code{padding:6px;font-weight:700}.success{display:grid;gap:4px;margin:24px 0;padding:16px;border-radius:12px;background:#e7f7ef;color:#18794e}.success span{font-size:13px}</style></head><body><main><p class="eyebrow">Account security</p><h1>Authenticator app</h1><p class="muted">Add a second factor so a password alone cannot sign in to your account.</p>${content}</main>${script}</body></html>`;
}
