CREATE DATABASE IF NOT EXISTS app_a_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS app_b_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

GRANT ALL PRIVILEGES ON auth_db.* TO 'platform'@'%';
GRANT ALL PRIVILEGES ON app_a_db.* TO 'platform'@'%';
GRANT ALL PRIVILEGES ON app_b_db.* TO 'platform'@'%';

GRANT CREATE, DROP, REFERENCES, ALTER ON *.* TO 'platform'@'%';

FLUSH PRIVILEGES;
